name: Dungeons
author: MankaiStep
version: 1.0
load: POSTWORLD
main: me.manaki.plugin.dungeons.Dungeons
depend: [MythicMobs]
softdepend: [Shops, Vault, FeatherBoard, PlaceholderAPI]
api-version: 1.16
loadbefore: [WorldGuard]
commands:
    dungeons:
        description: Plugin's commands
        aliases: [dadmin, d3, sd]
        permission: dungeon.command
    dungeon:
        description: Plugin's commands
        aliases: [d, phoban]